application:
  oauth:
    issuer: http://localhost:8081/api
    clients:
      default: # In future move this to DB
        client-id: default
        client-secret: default
        redirect-uri: http://localhost:8081/api/oauth2/callback/default
        public-client: false
        access-token-ttl: 1
        access-token-ttl-time-unit: MINUTES
        refresh-token-ttl: 1
        refresh-token-ttl-time-unit: DAYS
        authorities:
          - "read"
          - "write"

efi:
  pix:
    base-url: http://localhost:8081/api/mock-efi
    oauth-token-path: /oauth/token
    oauth-scopes: "cob.write cob.read pix.write pix.read pix.send webhook.write webhook.read"
    client-id: ${PIX_CLIENT_ID:""}
    client-secret: ${PIX_CLIENT_SECRET:""}
    p12-password: "test123"
    p12-local-path: certificates/test/test_cert.p12
    p12-source: local

redis:
  host: ${redis.hosts:localhost}
  port: ${redis.ports:6390}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:template;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE # change this to your database type, postgresql, mysql or other
  test:
    database:
      replace: none
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    locations: classpath:db/migration