application:
  otel:
    memory-exporter: false
  name: events-platform
  environment: ${DEPLOYMENT_ENVIRONMENT_NAME:dev}
  instance: events-platform-01

payments:
  efi:
    charges:
      enabled: true
      ngrok: true
      ngrok-url: http://ngrok:4040 # Only for dev with docker
      base-url: https://cobrancas-h.api.efipay.com.br
      notification-url: http://ngrok:8081/api/webhooks
      oauth-token-path: /v1/authorize
      skip-mtls-checking: true
      client-id: ${PIX_CLIENT_ID:""}
      client-secret: ${PIX_CLIENT_SECRET:""}
    pix:
      enabled: true
      ngrok: true
      ngrok-url: http://ngrok:4040 # Only for dev with docker
      base-url: https://pix-h.api.efipay.com.br
      oauth-token-path: /oauth/token
      skip-mtls-checking: true
      client-id: ${PIX_CLIENT_ID:""}
      client-secret: ${PIX_CLIENT_SECRET:""}
      pix-keys:
        - "71cdf9ba-c695-4e3c-b010-abb521a3f1be" # Test only
      p12-password:
      p12-local-path: certificates/homolog/homologacao-821156-events-platform-homolog.p12
      p12-source: local
  # e caso seja in memory
#  in-memory:
#    pix:
#      enabled: true
#      base-url: http://localhost:8081/api
#      pix-keys:
#        - "71cdf9ba-c695-4e3c-b010-abb521a3f1be" # Test only

web-client:
  payments:
    read-timeout: 2_000
    connect-timeout: 2_000

redis:
  host: localhost
  port: 6379

server:
  tomcat:
    threads:
      worker: 10
      io: 2

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:template;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE # change this to your database type, postgresql, mysql or other
  test:
    database:
      replace: none
  h2:
    console:
      enabled: true
      path: /h2
  #  datasource: # change this configurations to your database
  #    url: jdbc:postgresql://localhost:5434/events-platform
  #    username: postgres
  #    password: 123456
  jpa:
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  health:
    redis:
      enabled: false # Use this on redis is disabled in this profile

opentelemetry:
  metrics:
    #    endpoint: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT} # For Production
    endpoint: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://localhost:4317/v1/metrics} # For dev or sandbox